name: projeto
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  network_image: ^0.1.1
  flutter_svg: 1.1.6
  flutter_statusbarcolor_ns: ^0.5.0
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  dot_navigation_bar: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  email_validator: ^2.1.17
  flutter_spinkit: ^5.2.1
  google_sign_in: ^6.2.1
  firebase_database: ^10.4.9
  cloud_firestore: ^4.15.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - "lib/Image/SoccerImg.svg"
  - "lib/Image/SoccerImgSub.svg"
  - "lib/Image/facebookIcon.svg"
  - "lib/Image/googleIcon.svg"
  - "lib/Image/chat_box.svg"
  - "lib/Image/iconMessage.svg"
  
