name: projeto
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  network_image: ^0.1.1
  flutter_svg: ^2.0.9
  flutter_statusbarcolor_ns: ^0.5.0
  google_nav_bar: ^5.0.6
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - "lib/Image/SoccerImg.svg"
  - "lib/Image/SoccerImgSub.svg"
  - "lib/Image/facebookIcon.svg"
  - "lib/Image/googleIcon.svg"
  - "lib/Image/chat_box.svg"
  - "lib/Image/iconMessage.svg"
  
